# Class 13 Topics: Pivot, Apply, Regex, and Pandas Practice

This notebook covers the following:
1. Pivot in Pandas
2. Apply Function in Pandas
3. Basics of Regex in Python
4. Practice Exercises

Follow along and execute the code cells to explore each concept.

In [2]:
# Importing Libraries
import pandas as pd
import numpy as np
import re

## 1. Pivot Example

In [5]:
data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'City': ['New York', 'London', 'New York', 'London'],
    'Temperature': [32, 45, 30, 44]
}
df = pd.DataFrame(data)

df

         Date      City  Temperature
0  2024-01-01  New York           32
1  2024-01-01    London           45
2  2024-01-02  New York           30
3  2024-01-02    London           44

In [6]:
# Pivot the DataFrame
df = df.pivot(index = 'Date', columns = 'City', values = 'Temperature')
df

City        London  New York
Date
2024-01-01      45        32
2024-01-02      44        30

In [10]:
# Pivot the DataFrame
df = df.pivot(index = 'City', columns = 'Date', values = 'Temperature')
df

Date      2024-01-01  2024-01-02
City
London            45          44
New York          32          30

PRACTICE

In [13]:
# Question 1: Sales Analysis
data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01',
             '2024-01-02', '2024-01-02', '2024-01-02', '2024-01-02'],
    'Region': ['East', 'West', 'East', 'West', 'East', 'West', 'East', 'West'],
    'Product': ['Apples', 'Apples', 'Oranges', 'Oranges', 'Apples', 'Apples', 'Oranges', 'Oranges'],
    'Sales': [50, 30, 20, 40, 60, 25, 35, 45]
}

df = pd.DataFrame(data)
df

         Date Region  Product  Sales
0  2024-01-01   East   Apples     50
1  2024-01-01   West   Apples     30
2  2024-01-01   East  Oranges     20
3  2024-01-01   West  Oranges     40
4  2024-01-02   East   Apples     60
5  2024-01-02   West   Apples     25
6  2024-01-02   East  Oranges     35
7  2024-01-02   West  Oranges     45

In [25]:
# Task:

# Pivot the data to show the total sales for each product in each region, with the Date as the index and Region as columns.
df.pivot_table(index = ['Date', 'Product'], columns = 'Region', values = 'Sales', aggfunc='sum')

Region              East  West
Date       Product
2024-01-01 Apples     50    30
           Oranges    20    40
2024-01-02 Apples     60    25
           Oranges    35    45

In [26]:
# Question 2: Employee Work Hours
# You have the following data of employees and their daily work hours:
data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-01',
             '2024-01-02', '2024-01-02', '2024-01-02'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
    'Department': ['HR', 'IT', 'IT', 'HR', 'IT', 'IT'],
    'Hours Worked': [8, 6, 7, 9, 8, 6]
}

df = pd.DataFrame(data)
df

         Date Employee Department  Hours Worked
0  2024-01-01    Alice         HR             8
1  2024-01-01      Bob         IT             6
2  2024-01-01  Charlie         IT             7
3  2024-01-02    Alice         HR             9
4  2024-01-02      Bob         IT             8
5  2024-01-02  Charlie         IT             6

In [33]:
# Task:

# Create a pivot table that shows the total Hours Worked by each employee across all dates.
df.pivot_table(index='Employee', values= 'Hours Worked', aggfunc='sum')

          Hours Worked
Employee
Alice               17
Bob                 14
Charlie             13

## 2. Apply Function Example

Apply Function in Pandas

The `apply()` function in Pandas is used to apply a function along an axis of the DataFrame or Series.

It is a highly flexible method that allows you to apply custom or built-in functions to rows or columns.

**Key Points**:

**Element-wise Transformation**:  You can apply a function to modify values in
a column or row.

**Row/Column Operations**:  Use axis=0 to apply the function to columns (default) and axis=1 to apply it to rows.

**Supports Lambda Functions**:  Simplifies applying small, one-off functions.

**Works on Series and DataFrames**:  Can be applied to a single column or the entire DataFrame.

In [34]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df

   A  B
0  1  4
1  2  5
2  3  6

In [36]:
df[['A+5', 'B+6']] = df.apply(lambda x : pd.Series([x['A']+5, x['B']+6]),axis = 1)
df

   A  B  A+5  B+6
0  1  4    6   10
1  2  5    7   11
2  3  6    8   12

In [38]:
df['A=5'] = df['A'].apply(lambda x: x-5)

   A  B  A+5  B+6  A=5
0  1  4    6   10   -4
1  2  5    7   11   -3
2  3  6    8   12   -2

In [39]:
df.rename(columns = {'A=5':'A-5'}, inplace = True)
df

   A  B  A+5  B+6  A-5
0  1  4    6   10   -4
1  2  5    7   11   -3
2  3  6    8   12   -2

In [40]:
# Question 1: Calculate Age
# You have a DataFrame with employee birth years.
# Task:  Calculate their age based on the current year (2024).

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Birth Year': [1990, 1985, 2000]}
df = pd.DataFrame(data)
df

      Name  Birth Year
0    Alice        1990
1      Bob        1985
2  Charlie        2000

In [43]:
df['Age'] = df['Birth Year'].apply(lambda x : 2025-x )
df

      Name  Birth Year  Age
0    Alice        1990   35
1      Bob        1985   40
2  Charlie        2000   25

In [44]:
# Question 2: Categorize Scores
# You have student scores in a DataFrame. Categorize the scores as:

# Pass if score ≥ 50.
# Fail if score < 50.

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Score': [45, 85, 30]}
df = pd.DataFrame(data)
df

      Name  Score
0    Alice     45
1      Bob     85
2  Charlie     30

In [46]:
df['result'] = df['Score'].apply(lambda x : 'Pass' if x >= 50 else 'Fail')
df

      Name  Score result
0    Alice     45   Fail
1      Bob     85   Pass
2  Charlie     30   Fail

Normalized Value=
(Max Value - Min Value)/
(Value - Min Value)
​

In [53]:
# Question 3: Normalize Column Values
# You have a DataFrame with sales figures. Normalize the sales data to range between 0 and 1.

# DataFrame creation
data = {'Product': ['A', 'B', 'C','D'], 'Sales': [100, 300,360 ,500]}
df = pd.DataFrame(data)
df

  Product  Sales
0       A    100
1       B    300
2       C    360
3       D    500

In [57]:
max_ = max(df['Sales'])
min_ = min(df['Sales'])

#df['Cate'] = df['Sales'].apply(lambda x : (max_-min_)/(x - min_))

df['Normalized'] = df['Sales'].apply(lambda x : (x-df['Sales'].min())/(df['Sales'].max()-df['Sales'].min()))

df

  Product  Sales  Normalized
0       A    100        0.00
1       B    300        0.50
2       C    360        0.65
3       D    500        1.00

In [49]:
# Question 3: Normalize Column Values
# You have a DataFrame with sales figures. Normalize the sales data to range between 0 and 1.

# DataFrame creation
data = {'Product': ['A', 'B', 'C','D'], 'Sales': [100, 300,360 ,500]}
df = pd.DataFrame(data)
df

  Product  Sales
0       A    100
1       B    300
2       C    360
3       D    500

## 3. Basics of Regex

Regular expressions (regex) are a sequence of characters that define a search pattern. They are widely used for text matching, extraction, and substitution tasks.

Key Points:

Pattern Matching: Match specific sequences of characters in strings.

Flexible Search: Supports wildcards, ranges, and repetitions.

Functions: Common regex functions include findall(), search(), match(), and sub().

https://www.w3schools.com/python/python_regex.asp

https://regex101.com/r/lHs2R3/1

In [67]:
text = "My phone number is a 9876543210 986 047 ."
# Find the phone number

phone_num = re.findall('\d{5}', text)

phone_num

['98765', '43210']

In [68]:
text = "My phone number is a 9876543210 986 047 ."
# Find the phone number

phone_num = re.findall('\d+', text)

phone_num

['9876543210', '986', '047']

In [76]:
# Question 1: Validate Email Addresses
# Identify valid email addresses from a list.
emails = ['alice@example.com', 'bob_at_example.com', 'charlie@example.co.uk']

email  = [i for i in emails if re.match(r'^[\w.-]+@[\w.-]+\.\w+$',i)]
email

['alice@example.com', 'charlie@example.co.uk']

In [79]:
# Question 2: Extract Hashtags
# Extract all hashtags from a sentence.
text = "I love #Python and #MachineLearning!"
# Extract hashtags

fin = re.findall(r'#\w+',text)
fin

['#Python', '#MachineLearning']

In [85]:
# Question 3: Replace Dates with Placeholder
# Replace all dates in the format YYYY-MM-DD with [DATE].
text = "The meeting is on 2024-12-22."
# Replace dates
dat = re.sub(r'\d{4}-\d{2}-\d{2}', '[date]', text)
dat

'The meeting is on [date].'

In [82]:
# Question 4: Extract Phone Numbers
# Extract phone numbers from a string.
text = "Call me at 9876543210 or at 1234567890."
cal = re.findall(r'\d+', text)
cal

['9876543210', '1234567890']

## 4. Pandas Practice Example

## Practice Exercises

1. Create a DataFrame with sales data and pivot it.
2. Write a function to categorize temperatures (`Cold`, `Warm`, `Hot`) and apply it to a DataFrame.
3. Write a regex to extract email IDs from a string.
4. Calculate total pay for employees given hours worked and hourly rate.

In [22]:
# Find the phone number. text = "My phone number is a 9876543210 986 047."

text = "My phone number is a 9876543210 9876543210 986 047."

result = re.search(r'\d{10}', text)
result.group() # Returns first occurance of the match.

result1 = re.findall(r'\d{10}', text)
result1 # Returns all occurance of the match.

['9876543210', '9876543210']

In [56]:
# Identify valid email addresses from a list. 
emails = ["johnsmith@example.com","john.smith@example.com","john123@example.com","john_smith-jr@example.com","user@mail.hr.example.com","alice@example.co.uk","user@123domain.com","user@data.science.org","first.last+alias@example.com","\"user@strange\"@example.com", "John.Smith@Example.COM", "name@e-mail-server.com"]

result = [i for i in emails if re.search(r'[\w\._-]+@[\w_-]+\.\w+',i)]

result

['johnsmith@example.com',
 'john.smith@example.com',
 'john123@example.com',
 'john_smith-jr@example.com',
 'user@mail.hr.example.com',
 'alice@example.co.uk',
 'user@123domain.com',
 'user@data.science.org',
 'first.last+alias@example.com',
 'John.Smith@Example.COM',
 'name@e-mail-server.com']

In [58]:
# Extract all hashtags from a sentence. 
text = "I love #Python and #MachineLearning!"

result = re.findall(r'#\w+', text)
result

['#Python', '#MachineLearning']

In [61]:
# Replace all dates in the format YYYY-MM-DD with [DATE]. 

text = "The meeting is on 2024-12-22."

re.sub(r'\d+-\d+-\d+', "[DATE]", text)

'The meeting is on [DATE].'

In [65]:
# Extract phone numbers from a string. 
text = "Call me at 9876543210 or at 1234567890."
re.findall(r'\d{10}', text)

['9876543210', '1234567890']

In [68]:
# Use re.search() to extract the first number from a sentence.

text = "I walked 5 kilometers today and burned 300 calories."

re.search(r'\d', text).group()

'5'

In [77]:
# Use re.match() to check if a string starts with a capital letter.

text = "I walked 5 kilometers today and burned 300 calories."

re.match(r'[A-Z]', text).group() # re.match() returns an object .group() is used to extract the result.

'I'

In [79]:
# Use re.findall() to extract all email addresses from a paragraph.

paragraph = """
Please reach out to our team at support@example.com or marketing.team@business.co.uk.
For press inquiries, contact media@news.org. You can also connect with john_doe123@company.net.
"""

re.findall(r'[\w.+_]+@[\w.+_].[\w.+_]+', paragraph)

['support@example.com',
 'marketing.team@business.co.uk.',
 'media@news.org.',
 'john_doe123@company.net.']

In [80]:
# Extract all phone numbers of pattern xxx-xxx-xxxx from text using re.findall().

text = "You can reach us at 123-456-7890 or 987-654-3210. Emergency contact: 555-000-1111. Invalid: 12-3456-7890 or 1234567890."

re.findall(r'\d{3}-\d{3}-\d{4}', text)

['123-456-7890', '987-654-3210', '555-000-1111']

In [81]:
# Replace all digits in a string with # using re.sub().

text = "You can reach us at 123-456-7890 or 987-654-3210."

re.sub(r'\d', '#', text)

'You can reach us at ###-###-#### or ###-###-####.'

In [85]:
# Extract all hashtags from a tweet using regex.

tweet = "Loving the vibes at the beach! 🌊 #sunset #vacation #RelaxMode"

re.findall(r'#\w+', tweet)

['#sunset', '#vacation', '#RelaxMode']

In [86]:
# Validate if a given string is a valid date in format YYYY-MM-DD.

text = "The project began on 2023-05-12 and saw major updates on 2023-11-28 and 2024-02-30."

re.findall(r'\d{4}-\d{2}-\d{2}', text)

['2023-05-12', '2023-11-28', '2024-02-30']

In [99]:
# Extract all words that start with capital letters and are more than 5 characters long.

text = "Alexander traveled to California for the International Conference on Data Science. While there, he met Benjamin and participated in Workshops and Seminars hosted by Google and Microsoft."

re.findall(r'\b[A-Z][a-zA-Z]{5,}\b', text)

['Alexander',
 'California',
 'International',
 'Conference',
 'Science',
 'Benjamin',
 'Workshops',
 'Seminars',
 'Google',
 'Microsoft']

In [4]:
# Remove all special characters except alphabets and numbers from a text string.

text = "Hello is this for > $12"

re.sub(r'[^A-Za-z0-9]', '', text)

'Helloisthisfor12'

In [5]:
# Use regex to split a sentence into words ignoring punctuation.

sentence = "Hello, world! How's everything going?"
re.findall(r'\b\w+\b', sentence)

['Hello', 'world', 'How', 's', 'everything', 'going']

In [14]:
# Create a DataFrame with sales data and pivot it.

# Sample sales data
data = {
    "Date": ["2024-04-01", "2024-04-01", "2024-04-02", "2024-04-02", "2024-04-03"],
    "Product": ["Laptop", "Phone", "Tablet", "Laptop", "Phone"],
    "Units Sold": [5, 10, 3, 2, 7],
    "Unit Price": [1000, 500, 300, 1000, 500],
    "Region": ["North", "South", "East", "West", "North"]
}

# Create DataFrame
df = pd.DataFrame(data)

df['Total Sales'] = df['Unit Price']*df['Units Sold']

In [16]:
df.pivot(index = 'Region', columns = 'Product', values= 'Total Sales').fillna(0)

Product  Laptop   Phone  Tablet
Region
East        0.0     0.0   900.0
North    5000.0  3500.0     0.0
South       0.0  5000.0     0.0
West     2000.0     0.0     0.0

In [18]:
# Write a function to categorize temperatures (Cold, Warm, Hot) and apply it to a DataFrame.

data = {
    "Date": ["2024-04-01", "2024-04-01", "2024-04-02", "2024-04-02", "2024-04-03"],
    "City": ["Delhi", "Mumbai", "Delhi", "Mumbai", "Delhi"],
    "Temperature (C)": [15, 20, 36, 31, 37],
    "Condition": ["Sunny", "Cloudy", "Sunny", "Rainy", "Hot"]
}

# Create DataFrame
df = pd.DataFrame(data)

df['temp_cat'] = df['Temperature (C)'].apply(lambda x : 'Hot' if x > 20 else ('Warm' if x > 15 and x < 20 else 'Cold'))

In [26]:
df

         Date    City  Temperature (C) Condition temp_cat
0  2024-04-01   Delhi               15     Sunny     Cold
1  2024-04-01  Mumbai               20    Cloudy     Cold
2  2024-04-02   Delhi               36     Sunny      Hot
3  2024-04-02  Mumbai               31     Rainy      Hot
4  2024-04-03   Delhi               37       Hot      Hot

In [27]:
# Calculate total pay for employees given hours worked and hourly rate.

# Sample employee data
data = {
    "Employee": ["Alice", "Bob", "Charlie", "Diana", "Ethan"],
    "Hours Worked": [40, 35, 45, 30, 50],
    "Hourly Rate": [20, 22, 18, 25, 15]
}

# Create DataFrame
df = pd.DataFrame(data)

# Calculate Total Pay
df["Total Pay"] = df["Hours Worked"] * df["Hourly Rate"]

print(df)

  Employee  Hours Worked  Hourly Rate  Total Pay
0    Alice            40           20        800
1      Bob            35           22        770
2  Charlie            45           18        810
3    Diana            30           25        750
4    Ethan            50           15        750

In [28]:
# Create pivot table for average salary by department

# Sample employee data
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona'],
    'Department': ['HR', 'Finance', 'IT', 'Finance', 'IT', 'HR'],
    'Salary': [50000, 60000, 70000, 65000, 72000, 52000]
}

# Create DataFrame
df = pd.DataFrame(data)

# Create pivot table for average salary by department
pivot_table = df.pivot_table(index='Department', values='Salary', aggfunc='mean')

print(pivot_table)

             Salary
Department
Finance     62500.0
HR          51000.0
IT          71000.0

In [29]:
# Count the number of employees in each city using a pivot table.

# Sample employee data
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona'],
    'City': ['New York', 'Los Angeles', 'New York', 'Chicago', 'Chicago', 'Los Angeles']
}

# Create DataFrame
df = pd.DataFrame(data)

# Pivot table to count employees in each city
pivot_table = df.pivot_table(index='City', values='Employee', aggfunc='count')

print(pivot_table)

             Employee
City
Chicago             2
Los Angeles         2
New York            2

In [30]:
# Create a pivot table showing total sales by product

# Sample sales data
data = {
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone', 'Tablet'],
    'Units Sold': [5, 10, 3, 2, 7, 4],
    'Unit Price': [1000, 500, 300, 1000, 500, 300]
}

# Create DataFrame
df = pd.DataFrame(data)

# Calculate total sales
df['Total Sales'] = df['Units Sold'] * df['Unit Price']

# Create pivot table for total sales by product
pivot_table = df.pivot_table(index='Product', values='Total Sales', aggfunc='sum')

print(pivot_table)

         Total Sales
Product
Laptop          7000
Phone           8500
Tablet          2100

In [31]:
# Create a pivot table showing the average age by gender and department.

# Sample employee data
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona'],
    'Gender': ['Female', 'Male', 'Male', 'Female', 'Male', 'Female'],
    'Department': ['HR', 'Finance', 'IT', 'Finance', 'HR', 'IT'],
    'Age': [25, 30, 35, 40, 28, 22]
}

# Create DataFrame
df = pd.DataFrame(data)

# Create pivot table for average age by gender and department
pivot_table = df.pivot_table(index=['Gender', 'Department'], values='Age', aggfunc='mean')

print(pivot_table)

                    Age
Gender Department
Female Finance     40.0
       HR          25.0
       IT          22.0
Male   Finance     30.0
       HR          28.0
       IT          35.0

In [32]:
# Create a pivot table with multiple aggregation functions (mean and sum) for sales by region.

# Sample sales data
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'East', 'South', 'West', 'North'],
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone', 'Tablet'],
    'Units Sold': [5, 10, 3, 2, 7, 4, 8, 6, 3],
    'Unit Price': [1000, 500, 300, 1000, 500, 300, 1000, 500, 300]
}

# Create DataFrame
df = pd.DataFrame(data)

# Calculate total sales
df['Total Sales'] = df['Units Sold'] * df['Unit Price']

# Create pivot table with multiple aggregation functions (mean and sum) for sales by region
pivot_table = df.pivot_table(
    index='Region', 
    values='Total Sales', 
    aggfunc={'Total Sales': ['sum', 'mean']}
)

print(pivot_table)

               mean    sum
Region
East    1050.000000   2100
North   3133.333333   9400
South   6500.000000  13000
West    2500.000000   5000

In [ ]:
# Create pivot table with multiple aggregation functions (mean and sum) for sales by region


# Sample sales data
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'East', 'South', 'West', 'North'],
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone', 'Tablet'],
    'Units Sold': [5, 10, 3, 2, 7, 4, 8, 6, 3],
    'Unit Price': [1000, 500, 300, 1000, 500, 300, 1000, 500, 300]
}

# Create DataFrame
df = pd.DataFrame(data)

# Calculate total sales
df['Total Sales'] = df['Units Sold'] * df['Unit Price']

# Create pivot table with multiple aggregation functions (mean and sum) for sales by region
pivot_table = df.pivot_table(
    index='Region', 
    values='Total Sales', 
    aggfunc={'Total Sales': ['sum', 'mean']}
)

print(pivot_table)

In [ ]:
import pandas as pd

# Sample sales data
data = {
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone', 'Tablet'],
    'Units Sold': [5, 10, 3, 2, 7, 4, 8, 6, 3],
    'Unit Price': [1000, 500, 300, 1000, 500, 300, 1000, 500, 300]
}

# Create DataFrame
df = pd.DataFrame(data)

# Calculate total sales for each row
df['Total Sales'] = df['Units Sold'] * df['Unit Price']

# Pivot table: Total sales by product
pivot_table = df.pivot_table(
    index='Product', 
    values='Total Sales', 
    aggfunc='sum'
)

# Calculate overall total sales
overall_sales = pivot_table['Total Sales'].sum()

# Calculate percentage contribution of each product
pivot_table['Percentage Contribution'] = (pivot_table['Total Sales'] / overall_sales) * 100

# Print the pivot table
print(pivot_table)

In [3]:
# Create a pivot table with custom aggregation (e.g., standard deviation of scores by subject).


# Sample student scores data
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
    'Subject': ['Math', 'Math', 'Math', 'English', 'English', 'English', 'Science', 'Science', 'Science'],
    'Score': [88, 92, 85, 76, 81, 79, 91, 89, 94]
}

# Create DataFrame
df = pd.DataFrame(data)

# Create pivot table using standard deviation as aggregation
pivot_std = pd.pivot_table(
    df,
    index='Subject',
    values='Score',
    aggfunc=np.std
)

print(pivot_std)

            Score
Subject
English  2.516611
Math     3.511885
Science  2.516611

<ipython-input-3-5c243537fc98>:15: FutureWarning: The provided callable <function std at 0x7db3124789d0> is currently using DataFrameGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  pivot_std = pd.pivot_table(

In [5]:
# Use margins in a pivot table to include row and column totals.

# Sample sales data
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'East', 'South', 'West'],
    'Product': ['Laptop', 'Laptop', 'Phone', 'Tablet', 'Phone', 'Laptop', 'Tablet', 'Phone'],
    'Sales': [1000, 1200, 500, 700, 1500, 1300, 800, 600]
}

# Create DataFrame
df = pd.DataFrame(data)

# Pivot table with margins
pivot_table = pd.pivot_table(
    df,
    index='Region',
    columns='Product',
    values='Sales',
    aggfunc='sum',
    margins=True,
    margins_name='Total'  # Custom name for totals
)

print(pivot_table)

Product  Laptop   Phone  Tablet  Total
Region
East     1300.0   500.0     NaN   1800
North    1000.0  1500.0     NaN   2500
South    1200.0     NaN   800.0   2000
West        NaN   600.0   700.0   1300
Total    3500.0  2600.0  1500.0   7600

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

In [6]:
# Create a pivot table with a hierarchical index (multi-level rows and columns).

import pandas as pd

# Sample data
data = {
    'Region': ['North', 'North', 'South', 'South', 'East', 'East', 'West', 'West'],
    'Department': ['Sales', 'Tech', 'Sales', 'Tech', 'Sales', 'Tech', 'Sales', 'Tech'],
    'Product': ['Laptop', 'Laptop', 'Phone', 'Phone', 'Tablet', 'Tablet', 'Laptop', 'Phone'],
    'Quarter': ['Q1', 'Q2', 'Q1', 'Q2', 'Q1', 'Q2', 'Q1', 'Q2'],
    'Revenue': [1000, 1500, 900, 1100, 800, 1200, 950, 1050]
}

df = pd.DataFrame(data)

# Create pivot table with hierarchical index
pivot_table = pd.pivot_table(
    df,
    index=['Region', 'Department'],
    columns=['Quarter', 'Product'],
    values='Revenue',
    aggfunc='sum'
)

print(pivot_table)

Quarter                Q1                    Q2
Product            Laptop  Phone Tablet  Laptop   Phone  Tablet
Region Department
East   Sales          NaN    NaN  800.0     NaN     NaN     NaN
       Tech           NaN    NaN    NaN     NaN     NaN  1200.0
North  Sales       1000.0    NaN    NaN     NaN     NaN     NaN
       Tech           NaN    NaN    NaN  1500.0     NaN     NaN
South  Sales          NaN  900.0    NaN     NaN     NaN     NaN
       Tech           NaN    NaN    NaN     NaN  1100.0     NaN
West   Sales        950.0    NaN    NaN     NaN     NaN     NaN
       Tech           NaN    NaN    NaN     NaN  1050.0     NaN

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

In [7]:
# Filter a pivot table to show only values where the average sales exceed a threshold.

import pandas as pd

# Sample data
data = {
    'Region': ['North', 'North', 'South', 'South', 'East', 'East', 'West', 'West'],
    'Product': ['Laptop', 'Phone', 'Laptop', 'Phone', 'Tablet', 'Tablet', 'Laptop', 'Phone'],
    'Sales': [1200, 800, 1300, 950, 600, 1100, 1250, 900]
}

df = pd.DataFrame(data)

# Create pivot table: average sales by region and product
pivot = pd.pivot_table(
    df,
    index='Region',
    columns='Product',
    values='Sales',
    aggfunc='mean'
)

# Filter: show only values where average sales > 1000
filtered = pivot.where(pivot > 1000)

print(filtered)

Product  Laptop  Phone  Tablet
Region
East        NaN    NaN     NaN
North    1200.0    NaN     NaN
South    1300.0    NaN     NaN
West     1250.0    NaN     NaN

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()



Use regex to split a sentence into words ignoring punctuation.
Create a DataFrame with sales data and pivot it.

Write a function to categorize temperatures (Cold, Warm, Hot) and apply it to a DataFrame.

Calculate total pay for employees given hours worked and hourly rate.

Create a pivot table showing the average salary by department.

Count the number of employees in each city using a pivot table.

Create a pivot table showing total sales by product.

Create a pivot table showing the average age by gender and department.

Create a pivot table with multiple aggregation functions (mean and sum) for sales by region.

Create a pivot table showing percentage contribution of each product in overall sales.

Create a pivot table with custom aggregation (e.g., standard deviation of scores by subject).

Use margins in a pivot table to include row and column totals.

Create a pivot table with a hierarchical index (multi-level rows and columns).

Filter a pivot table to show only values where the average sales exceed a threshold.

Use .apply() to calculate the length of strings in a Name column.

Use .apply() to convert a list of dates from string to datetime.

Apply a function to standardize a column (z-score).

Use row-wise .apply() to calculate total marks from multiple score columns.

Apply a function that flags customers as "High" or "Low" value based on total purchase.

Use .apply() to extract the domain name from an email address column.

Apply a lambda function that returns different values based on multiple conditions (e.g., risk score).

Use .apply() on grouped data to calculate the range of each group.

Create a new column that computes weighted average of other columns using .apply().

Combine .apply() with np.where or nested if-else logic for complex row-wise classification.