https://colab.research.google.com/drive/1RqrMGIA0SU3P5kryRK1uV3AP8U2pcJes?usp=sharing

# Pandas Notes for Class 11

### **Introduction to Pandas**
**What is Pandas?**
- **Pandas** is a Python library used for data manipulation and analysis.
- It provides two primary data structures:
  1. **Series**: A one-dimensional array, similar to a list or column in Excel.
  2. **DataFrame**: A two-dimensional table, similar to a spreadsheet or SQL table.

**Why use Pandas?**
- Simplifies data cleaning, manipulation, and analysis tasks.
- Provides tools for:
  - Handling missing data.
  - Filtering and slicing datasets.
  - Performing operations like groupby, aggregation, and merging.

In [17]:
# Install Pandas (if not already installed)
!pip install pandas

# Import Pandas
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### **Creating a DataFrame**
A DataFrame is a table of rows and columns. Here's how to create one:

In [153]:
# Define data
data = {
        'Name':['sneha','Alice','bob','peter'],
        'Age': [27,28,np.nan,20],
        'City':['Hyd','Guj','Luk','Blg']
        }

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

    Name   Age City
0  sneha  27.0  Hyd
1  Alice  28.0  Guj
2    bob   NaN  Luk
3  peter  20.0  Blg

### **Understanding Pandas Methods**

#### **1. `df.head()`**
**Definition**: Displays the first `n` rows of the DataFrame (default is 5). It helps to quickly inspect the top portion of the dataset.

In [21]:
# View the first two rows
df.head(2)

    Name   Age City
0  sneha  27.0  Hyd
1  Alice  28.0  Guj

#### **2. `df.info()`**
**Definition**: Summarizes information about the DataFrame:
  - Total rows and columns.
  - Column names and data types.
  - Non-null values in each column.

In [3]:
# Show information about the DataFrame

#### **3. `df.tail()`**
**Definition**: Displays the last `n` rows of the DataFrame (default is 5). Useful to check the end of a dataset.

In [11]:
# View the last row
df.tail(2)

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

      Name   Age   City
2  Suruchi   NaN    SHB
3    Anuja  34.0  Korea

#### **4. `df.describe()`**
**Definition**: Provides summary statistics for numeric columns.
  - Includes count, mean, min, max, standard deviation, and quartiles.

In [154]:
df

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

    Name   Age City
0  sneha  27.0  Hyd
1  Alice  28.0  Guj
2    bob   NaN  Luk
3  peter  20.0  Blg

In [16]:
# Display statistical summary
df.describe()

             Age
count   3.000000
mean   25.000000
std     4.358899
min    20.000000
25%    23.500000
50%    27.000000
75%    27.500000
max    28.000000

In [156]:
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [161]:
d = {'score': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]}
df = pd.DataFrame(d)
print(df.quantile(0.5))

score    80.0
Name: 0.5, dtype: float64

### **Indexing in Pandas**
Indexing allows selecting specific rows and columns.

#### **5. `.loc` (Label-Based Indexing)**
**Definition**: Selects rows/columns using labels (names).
**Syntax**: `df.loc[row_label, column_label]`

In [18]:
# Select row 1 and column 'Name'

df.loc[1,'Name']

# Select rows 0 to 1 and columns 'Name' and 'City'
df.loc[0:1,['Name', 'City']]

    Name City
0  sneha  Hyd
1  Alice  Guj

In [29]:
# How do you filter rows based on a condition using .loc?
df.loc[df['Age']>25,'Name']

0    sneha
1    Alice
Name: Name, dtype: object

In [31]:
#  How do you fetch a column based on another column filter example: fetch names only whose age > 30

'sneha'

#### **6. `.iloc` (Position-Based Indexing)**
**Definition**: Selects rows/columns using integer positions.
**Syntax**: `df.iloc[row_index, column_index]`

In [32]:
# Select row 0 and column 1
df.iloc[0,0]
# Select rows 0 to 1 and columns 0 to 1
df.iloc[0:2,0:3]

    Name   Age City
0  sneha  27.0  Hyd
1  Alice  28.0  Guj

In [46]:
df[df['Name']=='sneha']

    Name   Age City
0  sneha  27.0  Hyd

In [47]:
df.iloc[::2]

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

    Name   Age City
0  sneha  27.0  Hyd
2    bob   NaN  Luk

### Practice

  * Basic Analysis

    Display the first 5 rows and the last 3 rows of the DataFrame.


 * Filtering

    * Find students who scored more than 85 in Math.
    * List all students with an average score (across all subjects) greater than 90.

* New Column

    * Add a Total column that sums up the scores for Math, Science, and English for each student.
    * Add an Average column that calculates the average score for each student.

* Sorting

    * Sort the DataFrame by the Math column in descending order.
    * Sort by the Total column in ascending order.

* Group Analysis (Challenge)

    * Group students based on their Math scores:

    Below 80: "Needs Improvement."

    80-90: "Good."

    Above 90: "Excellent."

    * Count the number of students in each group.

In [50]:
data = {
    'Student': ['John', 'Alice', 'Bob', 'Diana', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
        'Math': [85, 90, 78, 88, 92, 76, 85, 89, 81, 95],
        'Science': [92, 87, 83, 89, 85, 80, 88, 90, 84, 93],
        'English': [88, 84, 79, 91, 87, 81, 89, 92, 86, 94]
}

In [51]:
df = pd.DataFrame(data)

In [53]:
# Display the first 5 rows and the last 3 rows of the DataFrame.

df.head()
df.head(5)
df.tail(3)

  Student  Math  Science  English
7  Hannah    89       90       92
8     Ian    81       84       86
9    Jack    95       93       94

In [71]:
# Find students who scored more than 85 in Math.

df.loc[df['Math']>85]

  Student  Math  Science  English
1   Alice    90       87       84
3   Diana    88       89       91
4     Eve    92       85       87
7  Hannah    89       90       92
9    Jack    95       93       94

In [93]:
# List all students with an average score (across all subjects) greater than 90.

df[df.iloc[:,1:].mean(axis=1)>90]

  Student  Math  Science  English
7  Hannah    89       90       92
9    Jack    95       93       94

In [97]:
# Add a Total column that sums up the scores for Math, Science, and English for each student.
df['Total']= df.iloc[:,1:].sum(axis=1)

In [98]:
df

  Student  Math  Science  English  Total
0    John    85       92       88    265
1   Alice    90       87       84    261
2     Bob    78       83       79    240
3   Diana    88       89       91    268
4     Eve    92       85       87    264
5   Frank    76       80       81    237
6   Grace    85       88       89    262
7  Hannah    89       90       92    271
8     Ian    81       84       86    251
9    Jack    95       93       94    282

In [105]:
# Add an Average column that calculates the average score for each student.

df['Average'] = df.iloc[:,1:4].mean(axis=1)

In [106]:
df

  Student  Math  Science  English  Total    Average
0    John    85       92       88    265  88.333333
1   Alice    90       87       84    261  87.000000
2     Bob    78       83       79    240  80.000000
3   Diana    88       89       91    268  89.333333
4     Eve    92       85       87    264  88.000000
5   Frank    76       80       81    237  79.000000
6   Grace    85       88       89    262  87.333333
7  Hannah    89       90       92    271  90.333333
8     Ian    81       84       86    251  83.666667
9    Jack    95       93       94    282  94.000000

In [151]:
# Sort the DataFrame by Math in descending order:
# Reseting the index to get fresh index

df = df.sort_values(by="Math", ascending=False).reset_index(drop=True)
df

  Student  Math  Science  English  Total    Average      Math_feedback
0    Jack    95       93       94    282  94.000000           Exellent
1     Eve    92       85       87    264  88.000000           Exellent
2   Alice    90       87       84    261  87.000000               Good
3  Hannah    89       90       92    271  90.333333               Good
4   Diana    88       89       91    268  89.333333               Good
5    John    85       92       88    265  88.333333               Good
6   Grace    85       88       89    262  87.333333               Good
7     Ian    81       84       86    251  83.666667               Good
8     Bob    78       83       79    240  80.000000  Needs Improvement
9   Frank    76       80       81    237  79.000000  Needs Improvement

In [116]:
# Sort by the Total column in ascending order.
df.sort_values(by='Total')

  Student  Math  Science  English  Total    Average
5   Frank    76       80       81    237  79.000000
2     Bob    78       83       79    240  80.000000
8     Ian    81       84       86    251  83.666667
1   Alice    90       87       84    261  87.000000
6   Grace    85       88       89    262  87.333333
4     Eve    92       85       87    264  88.000000
0    John    85       92       88    265  88.333333
3   Diana    88       89       91    268  89.333333
7  Hannah    89       90       92    271  90.333333
9    Jack    95       93       94    282  94.000000

In [118]:
# Group students based on their Math scores:
# Below 80: "Needs Improvement."
# 80-90: "Good."
# Above 90: "Excellent."

# df['Math_feedback'] = [ for ]

def grade(x):
    if x < 80:
        return 'Needs Improvement'
    elif x >90:
        return 'Exellent'
    else:
        return 'Good'

In [120]:
df['Math_feedback'] = df['Math'].map(grade)

In [121]:
df

  Student  Math  Science  English  Total    Average      Math_feedback
9    Jack    95       93       94    282  94.000000           Exellent
4     Eve    92       85       87    264  88.000000           Exellent
1   Alice    90       87       84    261  87.000000               Good
7  Hannah    89       90       92    271  90.333333               Good
3   Diana    88       89       91    268  89.333333               Good
0    John    85       92       88    265  88.333333               Good
6   Grace    85       88       89    262  87.333333               Good
8     Ian    81       84       86    251  83.666667               Good
2     Bob    78       83       79    240  80.000000  Needs Improvement
5   Frank    76       80       81    237  79.000000  Needs Improvement

In [149]:
# Count the number of students in each group.
df.groupby('Math_feedback').count()['Student']

Math_feedback
Exellent             2
Good                 6
Needs Improvement    2
Name: Student, dtype: int64

# **Pandas Methods Overview**

### **1. DataFrame Creation & Viewing**
- `pd.DataFrame()`: Converts lists, dictionaries, or NumPy arrays into a DataFrame.
- `df.head(n)`: Displays the first `n` rows of the DataFrame (default is 5).
- `df.tail(n)`: Displays the last `n` rows of the DataFrame (default is 5).
- `df.info()`: Provides a summary of the DataFrame, including column names, non-null counts, and data types.
- `df.shape`: Returns the number of rows and columns in the DataFrame.
- `df.columns`: Returns a list of column names.
- `df.index`: Returns the row labels (index).
- `df.describe()`: Returns a statistical summary of numerical columns.

### **2. Indexing & Selection**
- `df['column_name']`: Access a single column.
- `df[['col1', 'col2']]`: Access multiple columns.
- `df.loc[]`: Label-based indexing for rows/columns.
- `df.iloc[]`: Position-based indexing for rows/columns.
- `df.at[]`: Fast access to a single value by label.
- `df.iat[]`: Fast access to a single value by index position.
- `df.xs()`: Access a cross-section of rows/columns.

### **3. Data Manipulation**
- `df.sort_values()`: Sort by one or more columns.
- `df.sort_index()`: Sort by row index.
- `df.drop()`: Drop rows or columns by label.
- `df.rename()`: Rename columns or rows.
- `df.set_index()`: Set a column as the new index.
- `df.reset_index()`: Reset the index and convert it into a column.
- `df.replace()`: Replace specified values with others.
- `df.fillna()`: Fill missing values with a specified value.
- `df.dropna()`: Drop rows or columns with missing values.
- `df.astype()`: Change the data type of a column.
- `df.apply()`: Apply a function along an axis (rows/columns).
- `df.applymap()`: Apply a function to every element in a DataFrame.
- `df.map()`: Map values from a dictionary or function to a Series.

### **4. Aggregation & Grouping**
- `df.groupby()`: Group the DataFrame by one or more columns.
- `df.agg()`: Apply multiple aggregation functions to grouped data.
- `df.transform()`: Apply a function to each group independently.
- `df.pivot_table()`: Create a pivot table for summarization.

### **5. Data Joining & Merging**
- `pd.merge()`: Merge two DataFrames on a common column or index.
- `df.join()`: Join DataFrames by index.
- `df.concat()`: Concatenate DataFrames along rows or columns.

### **6. String Operations**
- `df['column'].str()`: Perform vectorized string operations (e.g., `.lower()`, `.upper()`, `.contains()`, `.replace()`).

### **7. Handling Time Series Data**
- `pd.to_datetime()`: Convert strings or other formats to datetime.
- `df.resample()`: Resample time-series data.
- `df.shift()`: Shift data by a specified period.
- `df.rolling()`: Apply a rolling window operation for statistics like moving averages.

### **8. Missing Data Handling**
- `df.isna()`: Check for missing values.
- `df.notna()`: Check for non-missing values.
- `df.isnull()`: Same as `isna()`.
- `df.notnull()`: Same as `notna()`.

### **9. Numerical Operations**
- `df.sum()`: Sum of values along columns or rows.
- `df.mean()`: Mean of values along columns or rows.
- `df.median()`: Median of values along columns or rows.
- `df.min()`: Minimum value along columns or rows.
- `df.max()`: Maximum value along columns or rows.
- `df.cumsum()`: Cumulative sum.
- `df.cumprod()`: Cumulative product.

### **10. Pivoting**
- `df.pivot()`: Pivot data based on column values.
- `df.melt()`: Unpivot DataFrame from wide to long format.

### **11. Visualization**
- `df.plot()`: Simple plotting (line, bar, etc.) using Matplotlib.
- `df.hist()`: Plot histograms of numeric columns.

### **12. Working with Categories**
- `df['column'].astype('category')`: Convert a column to a categorical data type.
- `df['column'].cat.codes`: Access category codes of a categorical column.

### **13. Performance**
- `df.memory_usage()`: Check memory usage of the DataFrame.
- `df.memory_usage(deep=True)`: Detailed memory usage, especially for object columns.